// Generated by SmartIntake Admin Console from active SmartIntake questions and optional packaged controls.
// Do not hand-edit registry entries; update question UI_Control__c and use Sync Custom Control Registry.
const CONTROL_ALIASES = {
    "c/smartintakeoptioncardpicker": "DIRECT_SMARTINTAKEOPTIONCARDPICKER",
    "c/eventpulserating": "EVENT_PULSE",
    "c/smartintakeproductselector": "SMARTINTAKE_PRODUCT_SELECTOR",
    "c/smilerating": "SMILE_RATING",
    "c/testrating": "STAR_RATING",
    "direct_smartintakeoptioncardpicker": "DIRECT_SMARTINTAKEOPTIONCARDPICKER",
    "event_pulse": "EVENT_PULSE",
    "event_pulse_rating": "EVENT_PULSE",
    "progress": "EVENT_PULSE",
    "pulse": "EVENT_PULSE",
    "pulse_rating": "EVENT_PULSE",
    "smile": "SMILE_RATING",
    "smile_rating": "SMILE_RATING",
    "star": "STAR_RATING",
    "star_rating": "STAR_RATING"
};

const CONTROL_LOADERS = {
    "DIRECT_SMARTINTAKEOPTIONCARDPICKER": () => import("c/smartIntakeOptionCardPicker"),
    "EVENT_PULSE": () => import("c/eventPulseRating"),
    "SMARTINTAKE_PRODUCT_SELECTOR": () => import("c/smartIntakeProductSelector"),
    "SMILE_RATING": () => import("c/smileRating"),
    "STAR_RATING": () => import("c/testRating")
};

export function normalizeSmartIntakeControlKey(uiControl) {
    const rawValue = (uiControl || '').trim();
    if (!rawValue) {
        return '';
    }

    const normalized = rawValue.toLowerCase();
    return CONTROL_ALIASES[normalized] || rawValue.trim().toUpperCase();
}

export function isSmartIntakeRegisteredControl(uiControl) {
    return Boolean(CONTROL_LOADERS[normalizeSmartIntakeControlKey(uiControl)]);
}

export async function loadSmartIntakeControl(uiControl) {
    const loader = CONTROL_LOADERS[normalizeSmartIntakeControlKey(uiControl)];
    if (!loader) {
        return undefined;
    }

    const module = await loader();
    return module.default;
}